version: 3

env:
  DEBUG: true

tasks:
  git:push:
    aliases: [gp]
    desc: Pushes any staged commits to the remote repository.
    cmds: [git push --all --tags]

  pretty:
    aliases: [p, format, fmt]
    silent: false
    desc: Uses the Prettier CLI tool to format the codebase.
    cmds: ['prettier --write .']

  lint:
    aliases: [l]
    silent: false
    desc: Uses the Prettier CLI tool to lint the codebase.
    cmds: [prettier -c .]

  clean:
    aliases: [c]
    silent: false
    desc: Deletes local build/package directories.
    cmds: ['rm -rf node_modules pnpm-lock.yaml dist']

  build:
    aliases: [b]
    cmds: ['npm i', 'npm run build']
